float4 out gl_Position : POSITION;
float3 out oColor : TEXCOORD0_HALF;
float2 out oTexCoords : TEXCOORD1;
float out oPolygonIndex : TEXCOORD2;

void main(float4 position, float3 texCoords, float4 viewport, float3 color) {
    oColor = color / 31.0;
    oTexCoords = texCoords.xy;
    oPolygonIndex = texCoords[2];
    gl_Position = position;
    gl_Position.xy = 255.0 / float2(256.0, 191.0) * ((viewport.zw - viewport.xy) * (gl_Position.xy + gl_Position.w)) - gl_Position.w;
}
