float4 out gl_Position : POSITION;
float4 out oColor : TEXCOORD0_HALF;
float2 out oTexCoords : TEXCOORD1;

void main(float4 position, float2 texCoords, float4 viewport, float4 color) {
    oColor = color / 31.0;
    oTexCoords = texCoords;
    float2 screenDims = float2(255.0, 191.0);
    gl_Position = position;
    gl_Position.xy = (gl_Position.w * (viewport.zw + viewport.xy - screenDims) + (viewport.zw - viewport.xy) * gl_Position.xy) / screenDims;
}
