use crate::core::emu::Emu;
use crate::core::hle::bios::*;
use crate::core::CpuType::{ARM7, ARM9};

pub const ARM9_SWI_LOOKUP_TABLE: [(&str, fn(&mut Emu)); 33] = [
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("wait_by_loop", wait_by_loop::<{ ARM9 }>),
    ("interrupt_wait", interrupt_wait::<{ ARM9 }>),
    ("v_blank_intr_wait", v_blank_intr_wait::<{ ARM9 }>),
    ("halt", halt::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("divide", divide::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("cpu_set", cpu_set::<{ ARM9 }>),
    ("cpu_fast_set", cpu_fast_set::<{ ARM9 }>),
    ("square_root", square_root::<{ ARM9 }>),
    ("get_crc16", get_crc16::<{ ARM9 }>),
    ("is_debugger", is_debugger::<{ ARM9 }>),
    ("bit_unpack", bit_unpack::<{ ARM9 }>),
    ("lz77_uncomp", lz77_uncomp::<{ ARM9 }>),
    ("lz77_uncomp", lz77_uncomp::<{ ARM9 }>),
    ("huff_uncomp", huff_uncomp::<{ ARM9 }>),
    ("runlen_uncomp", runlen_uncomp::<{ ARM9 }>),
    ("runlen_uncomp", runlen_uncomp::<{ ARM9 }>),
    ("diff_unfilt8", diff_unfilt8::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("diff_unfilt16", diff_unfilt16::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
    ("unknown", unknown::<{ ARM9 }>),
];

pub const ARM7_SWI_LOOKUP_TABLE: [(&str, fn(&mut Emu)); 33] = [
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("wait_by_loop", wait_by_loop::<{ ARM7 }>),
    ("interrupt_wait", interrupt_wait::<{ ARM7 }>),
    ("v_blank_intr_wait", v_blank_intr_wait::<{ ARM7 }>),
    ("halt", halt::<{ ARM7 }>),
    ("sleep", sleep::<{ ARM7 }>),
    ("sound_bias", sound_bias::<{ ARM7 }>),
    ("divide", divide::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("cpu_set", cpu_set::<{ ARM7 }>),
    ("cpu_fast_set", cpu_fast_set::<{ ARM7 }>),
    ("square_root", square_root::<{ ARM7 }>),
    ("get_crc16", get_crc16::<{ ARM7 }>),
    ("is_debugger", is_debugger::<{ ARM7 }>),
    ("bit_unpack", bit_unpack::<{ ARM7 }>),
    ("lz77_uncomp", lz77_uncomp::<{ ARM7 }>),
    ("lz77_uncomp", lz77_uncomp::<{ ARM7 }>),
    ("huff_uncomp", huff_uncomp::<{ ARM7 }>),
    ("runlen_uncomp", runlen_uncomp::<{ ARM7 }>),
    ("runlen_uncomp", runlen_uncomp::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("get_sine_table", get_sine_table::<{ ARM7 }>),
    ("get_pitch_table", get_pitch_table::<{ ARM7 }>),
    ("get_volume_table", get_volume_table::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
    ("unknown", unknown::<{ ARM7 }>),
];
