use crate::jit::disassembler::thumb::alu_instructions_thumb::*;
use crate::jit::disassembler::thumb::branch_instructions_thumb::*;
use crate::jit::disassembler::thumb::delegations_thumb::*;
use crate::jit::disassembler::thumb::transfer_instructions_thumb::*;
use crate::jit::inst_info_thumb::InstInfoThumb;
use crate::jit::op::{MultipleTransfer, SingleTransfer};
use crate::jit::Op;
use crate::jit::Op::*;

pub fn lookup_thumb_opcode(opcode: u16) -> &'static (Op, fn(u16, Op) -> InstInfoThumb) {
    &LOOKUP_TABLE[((opcode >> 6) & 0x3FF) as usize]
}

static LOOKUP_TABLE: [(Op, fn(u16, Op) -> InstInfoThumb); 1024] = [
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LslT, lsl_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (LsrT, lsr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AsrT, asr_imm_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (AddT, add_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (SubT, sub_reg_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (AddT, add_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (SubT, sub_imm3_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (MovT, mov_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (CmpT, cmp_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (AddT, add_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (SubT, sub_imm8_t),
    (AndT, and_dp_t),
    (EorT, eor_dp_t),
    (LslT, lsl_dp_t),
    (LsrT, lsr_dp_t),
    (AsrT, asr_dp_t),
    (AdcT, adc_dp_t),
    (SbcT, sbc_dp_t),
    (RorT, ror_dp_t),
    (TstT, tst_dp_t),
    (NegT, neg_dp_t),
    (CmpT, cmp_dp_t),
    (CmnT, cmn_dp_t),
    (OrrT, orr_dp_t),
    (MulT, mul_dp_t),
    (BicT, bic_dp_t),
    (MvnT, mvn_dp_t),
    (AddHT, add_h_t),
    (AddHT, add_h_t),
    (AddHT, add_h_t),
    (AddHT, add_h_t),
    (CmpHT, cmp_h_t),
    (CmpHT, cmp_h_t),
    (CmpHT, cmp_h_t),
    (CmpHT, cmp_h_t),
    (MovHT, mov_h_t),
    (MovHT, mov_h_t),
    (MovHT, mov_h_t),
    (MovHT, mov_h_t),
    (BxRegT, bx_reg_t),
    (BxRegT, bx_reg_t),
    (BlxRegT, blx_reg_t),
    (BlxRegT, blx_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_pc_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 0)), ldrsb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (LdrT(SingleTransfer::new(true, false, true, true, 1)), ldrsh_reg_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 0)), strb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 0)), ldrb_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 1)), strh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 1)), ldrh_imm5_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (StrT(SingleTransfer::new(true, false, true, false, 2)), str_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (LdrT(SingleTransfer::new(true, false, true, false, 2)), ldr_sp_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddPcT, add_pc_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpT, add_sp_t),
    (AddSpImmT, add_sp_imm_t),
    (AddSpImmT, add_sp_imm_t),
    (AddSpImmT, add_sp_imm_t),
    (AddSpImmT, add_sp_imm_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_lr_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_lr_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_lr_t),
    (StmT(MultipleTransfer::new(true, true, false, false)), push_lr_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_pc_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_pc_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_pc_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), pop_pc_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (StmT(MultipleTransfer::new(false, true, true, false)), stmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (LdmT(MultipleTransfer::new(false, true, true, false)), ldmia_t),
    (BeqT, beq_t),
    (BeqT, beq_t),
    (BeqT, beq_t),
    (BeqT, beq_t),
    (BneT, bne_t),
    (BneT, bne_t),
    (BneT, bne_t),
    (BneT, bne_t),
    (BcsT, bcs_t),
    (BcsT, bcs_t),
    (BcsT, bcs_t),
    (BcsT, bcs_t),
    (BccT, bcc_t),
    (BccT, bcc_t),
    (BccT, bcc_t),
    (BccT, bcc_t),
    (BmiT, bmi_t),
    (BmiT, bmi_t),
    (BmiT, bmi_t),
    (BmiT, bmi_t),
    (BplT, bpl_t),
    (BplT, bpl_t),
    (BplT, bpl_t),
    (BplT, bpl_t),
    (BvsT, bvs_t),
    (BvsT, bvs_t),
    (BvsT, bvs_t),
    (BvsT, bvs_t),
    (BvcT, bvc_t),
    (BvcT, bvc_t),
    (BvcT, bvc_t),
    (BvcT, bvc_t),
    (BhiT, bhi_t),
    (BhiT, bhi_t),
    (BhiT, bhi_t),
    (BhiT, bhi_t),
    (BlsT, bls_t),
    (BlsT, bls_t),
    (BlsT, bls_t),
    (BlsT, bls_t),
    (BgeT, bge_t),
    (BgeT, bge_t),
    (BgeT, bge_t),
    (BgeT, bge_t),
    (BltT, blt_t),
    (BltT, blt_t),
    (BltT, blt_t),
    (BltT, blt_t),
    (BgtT, bgt_t),
    (BgtT, bgt_t),
    (BgtT, bgt_t),
    (BgtT, bgt_t),
    (BleT, ble_t),
    (BleT, ble_t),
    (BleT, ble_t),
    (BleT, ble_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (UnkThumb, unk_t),
    (SwiT, swi_t),
    (SwiT, swi_t),
    (SwiT, swi_t),
    (SwiT, swi_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BT, b_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlxOffT, blx_off_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlSetupT, bl_setup_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
    (BlOffT, bl_off_t),
];
