pub mod dma;
pub mod io_ports;
mod io_ports_arm7;
mod io_ports_arm9;
pub mod main_memory;
pub mod mem_handler;
pub mod oam_context;
pub mod palettes_context;
pub mod regions;
pub mod tcm_context;
pub mod vram_context;
pub mod wram_context;
