float3 out screenPos : TEXCOORD0;
float4 out gl_Position : POSITION;

uniform int bgCnts[4];

void main(float3 position) {
    short bgNum = short(position.z);
    int bgCnt = bgCnts[bgNum];
    int priority = bgCnt & 3;

    screenPos = float3((position.x * 0.5 + 0.5) * 256.0 - 0.1, position.y - 0.1, position.z);
    gl_Position = float4(position.x, 1.0 - position.y / 192.0 * 2.0, float(priority + 1) / 5.0, 1.0);
}
