float2 in screenPosWidescreen : TEXCOORD3;

void main(out float4 color : COLOR) {
    color = tex2D(display3dTex, screenPosWidescreen);
    if (!canDisplay()) {
        discard;
    }

    if (color.a == 0.0) {
        discard;
    }

    int bgCnt = getBgCnt();
    unsigned char priority = bgCnt & 3;
    unsigned char alpha = unsigned char(color.a * 31.0);
    unsigned char data = priority | (alpha << 2);
    color.a = float(data) / 255.0;
}
