float4 out gl_Position : POSITION;
float2 out screenPos : TEXCOORD0;
float2 out screenPosF : TEXCOORD1;
float2 out affineDims : TEXCOORD2;

void main(float2 position) {
    float normX = position.x * 0.5 + 0.5;
    screenPos = float2(max(normX * 256.0 - 0.1, 0.0), max(position.y - 0.1, 0.0));
    screenPosF = float2(normX, position.y / 192.0);
    affineDims = float2(0.0, 0.0);
    gl_Position = float4(position.x, 1.0 - screenPosF.y * 2.0, 0.0, 1.0);
}
