use crate::hle::bios::*;
use crate::hle::registers::ThreadRegs;

pub const ARM9_SWI_LOOKUP_TABLE: [(&'static str, fn(&mut ThreadRegs)); 33] = [
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("wait_by_loop", wait_by_loop),
    ("interrupt_wait", interrupt_wait),
    ("v_blank_intr_wait", v_blank_intr_wait),
    ("halt", halt),
    ("unknown", unknown),
    ("unknown", unknown),
    ("divide", divide),
    ("unknown", unknown),
    ("cpu_set", cpu_set),
    ("cpu_fast_set", cpu_fast_set),
    ("square_root", square_root),
    ("get_crc16", get_crc16),
    ("is_debugger", is_debugger),
    ("bit_unpack", bit_unpack),
    ("lz77_uncomp", lz77_uncomp),
    ("lz77_uncomp", lz77_uncomp),
    ("huff_uncomp", huff_uncomp),
    ("runlen_uncomp", runlen_uncomp),
    ("runlen_uncomp", runlen_uncomp),
    ("diff_unfilt8", diff_unfilt8),
    ("unknown", unknown),
    ("diff_unfilt16", diff_unfilt16),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
    ("unknown", unknown),
];
