#!/usr/bin/env python3
# Generate src/jit/interpreter/thumb_table.rs from the disassembler's own
# lookup_table_thumb.rs layout, so jit decode and interpreter decode can never disagree.
# Thumb disassembler fn names map 1:1 to interpreter handler names; anything the
# interpreter doesn't cover maps to inst_undefined_t.
import re, sys

SRC = "src/jit/disassembler/thumb/lookup_table_thumb.rs"
DST = "src/jit/interpreter/thumb_table.rs"

# Disassembler fn name -> interpreter handler. Identity for everything implemented.
FALLBACK = {"unk_t", "swi_t"}

names = []
in_table = False
for line in open(SRC):
    if "static LOOKUP_TABLE" in line:
        in_table = True
        continue
    if not in_table:
        continue
    if line.strip() == "];":
        break
    m = re.search(r", ([a-z0-9_]+)\),?\s*$", line)
    if m:
        names.append(m.group(1))

assert len(names) == 1024, f"expected 1024 entries, got {len(names)}"

handlers = ["inst_undefined_t" if n in FALLBACK else n for n in names]

with open(DST, "w") as f:
    f.write(
        "// AUTOGENERATED from src/jit/disassembler/thumb/lookup_table_thumb.rs layout. Do not edit by hand.\n"
        "// Each entry is the specialized interpreter handler for that opcode class, mirroring the\n"
        "// disassembler's flat lookup table (and NooDS' thumbInstrs). Unimplemented classes -> inst_undefined_t.\n"
        "#[rustfmt::skip]\n"
        "pub(super) static THUMB_TABLE: [ThumbInterpFn; 1024] = [\n"
    )
    for i in range(0, 1024, 4):
        f.write("    " + ", ".join(handlers[i : i + 4]) + ",\n")
    f.write("];\n")

print(f"wrote {DST} with {len(handlers)} entries, {sum(1 for h in handlers if h == 'inst_undefined_t')} fallbacks")
