use crate::core::div_sqrt::DivSqrt;
use crate::core::emu::{get_cm, get_cm_mut, get_common_mut, get_cpu_regs, get_cpu_regs_mut, get_mem, get_mem_mut, Emu};
use crate::core::memory::dma::Dma;
use crate::core::timers::Timers;
use crate::core::CpuType::ARM9;
use crate::logging::debug_println;
use crate::utils::Convert;
use dsvita_macros::{io_ports_read, io_ports_write};
use std::mem;

pub struct IoArm9 {
    div_sqrt: DivSqrt,
    pub dma: Dma,
    pub timers: Timers,
}

impl IoArm9 {
    pub fn new() -> Self {
        IoArm9 {
            div_sqrt: DivSqrt::new(),
            dma: Dma::new(ARM9),
            timers: Timers::new(ARM9),
        }
    }

    pub fn read<T: Convert>(&mut self, addr_offset: u32, emu: &mut Emu) -> T {
        /*
         * Use moving windows to handle reads and writes
         * |0|0|0|  x  |   x   |   x   |   x   |0|0|0|
         *         addr   + 1     + 2     + 3
         */
        let mut bytes_window = [0u8; 10];

        let mut addr_offset_tmp = addr_offset;
        let mut index = 3usize;
        let common = get_common_mut!(emu);
        while (index - 3) < mem::size_of::<T>() {
            io_ports_read!(match addr_offset + (index - 3) as u32 {
                io32(0x0) => common.gpu.gpu_2d_regs_a.get_disp_cnt(),
                io16(0x4) => common.gpu.get_disp_stat::<{ ARM9 }>(),
                io16(0x6) => common.gpu.v_count,
                io16(0x8) => common.gpu.gpu_2d_regs_a.get_bg_cnt(0),
                io16(0xA) => common.gpu.gpu_2d_regs_a.get_bg_cnt(1),
                io16(0xC) => common.gpu.gpu_2d_regs_a.get_bg_cnt(2),
                io16(0xE) => common.gpu.gpu_2d_regs_a.get_bg_cnt(3),
                io16(0x48) => common.gpu.gpu_2d_regs_a.win_in,
                io16(0x4A) => common.gpu.gpu_2d_regs_a.win_out,
                io16(0x50) => common.gpu.gpu_2d_regs_a.bld_cnt,
                io16(0x52) => common.gpu.gpu_2d_regs_a.bld_alpha,
                io16(0x60) => common.gpu.get_renderer().renderer_3d.get_disp_3d_cnt(),
                io32(0x64) => common.gpu.disp_cap_cnt,
                io16(0x6C) => todo!(),
                io32(0xB0) => self.dma.get_sad::<0>(),
                io32(0xB4) => self.dma.get_dad::<0>(),
                io32(0xB8) => self.dma.get_cnt::<0>(),
                io32(0xBC) => self.dma.get_sad::<1>(),
                io32(0xC0) => self.dma.get_dad::<1>(),
                io32(0xC4) => self.dma.get_cnt::<1>(),
                io32(0xC8) => self.dma.get_sad::<2>(),
                io32(0xCC) => self.dma.get_dad::<2>(),
                io32(0xD0) => self.dma.get_cnt::<2>(),
                io32(0xD4) => self.dma.get_sad::<3>(),
                io32(0xD8) => self.dma.get_dad::<3>(),
                io32(0xDC) => self.dma.get_cnt::<3>(),
                io32(0xE0) => self.dma.get_fill::<0>(),
                io32(0xE4) => self.dma.get_fill::<1>(),
                io32(0xE8) => self.dma.get_fill::<2>(),
                io32(0xEC) => self.dma.get_fill::<3>(),
                io16(0x100) => self.timers.get_cnt_l::<0>(get_cm!(emu)),
                io16(0x102) => self.timers.get_cnt_h::<0>(),
                io16(0x104) => self.timers.get_cnt_l::<1>(get_cm!(emu)),
                io16(0x106) => self.timers.get_cnt_h::<1>(),
                io16(0x108) => self.timers.get_cnt_l::<2>(get_cm!(emu)),
                io16(0x10A) => self.timers.get_cnt_h::<2>(),
                io16(0x10C) => self.timers.get_cnt_l::<3>(get_cm!(emu)),
                io16(0x10E) => self.timers.get_cnt_h::<3>(),
                io16(0x130) => common.input.get_key_input(),
                io16(0x180) => common.ipc.get_sync_reg::<{ ARM9 }>(),
                io16(0x184) => common.ipc.get_fifo_cnt::<{ ARM9 }>(),
                io16(0x1A0) => common.cartridge.get_aux_spi_cnt::<{ ARM9 }>(),
                io8(0x1A2) => common.cartridge.get_aux_spi_data::<{ ARM9 }>(),
                io32(0x1A4) => common.cartridge.get_rom_ctrl::<{ ARM9 }>(),
                io8(0x208) => get_cpu_regs!(emu, ARM9).ime,
                io32(0x210) => get_cpu_regs!(emu, ARM9).ie,
                io32(0x214) => get_cpu_regs!(emu, ARM9).irf,
                io8(0x240) => get_mem!(emu).vram.cnt[0],
                io8(0x242) => get_mem!(emu).vram.cnt[1],
                io8(0x243) => get_mem!(emu).vram.cnt[2],
                io8(0x241) => get_mem!(emu).vram.cnt[3],
                io8(0x244) => get_mem!(emu).vram.cnt[4],
                io8(0x245) => get_mem!(emu).vram.cnt[5],
                io8(0x246) => get_mem!(emu).vram.cnt[6],
                io8(0x247) => get_mem!(emu).wram.cnt,
                io8(0x248) => get_mem!(emu).vram.cnt[7],
                io8(0x249) => get_mem!(emu).vram.cnt[8],
                io16(0x280) => self.div_sqrt.div_cnt,
                io32(0x290) => self.div_sqrt.get_div_numer_l(),
                io32(0x294) => self.div_sqrt.get_div_numer_h(),
                io32(0x298) => self.div_sqrt.get_div_denom_l(),
                io32(0x29C) => self.div_sqrt.get_div_denom_h(),
                io32(0x2A0) => self.div_sqrt.get_div_result_l(),
                io32(0x2A4) => self.div_sqrt.get_div_result_h(),
                io32(0x2A8) => self.div_sqrt.get_divrem_result_l(),
                io32(0x2AC) => self.div_sqrt.get_divrem_result_h(),
                io16(0x2B0) => self.div_sqrt.sqrt_cnt,
                io32(0x2B4) => self.div_sqrt.sqrt_result,
                io32(0x2B8) => self.div_sqrt.get_sqrt_param_l(),
                io32(0x2BC) => self.div_sqrt.get_sqrt_param_h(),
                io8(0x300) => get_cpu_regs!(emu, ARM9).post_flg,
                io16(0x304) => common.gpu.pow_cnt1,
                io32(0x600) => common.gpu.gpu_3d_regs.get_gx_stat(),
                io32(0x604) => todo!(),
                io32(0x620) => todo!(),
                io32(0x624) => todo!(),
                io32(0x628) => todo!(),
                io32(0x62C) => todo!(),
                io16(0x630) => todo!(),
                io16(0x632) => todo!(),
                io16(0x634) => todo!(),
                io32(0x640) => common.gpu.gpu_3d_regs.get_clip_mtx_result(0),
                io32(0x644) => common.gpu.gpu_3d_regs.get_clip_mtx_result(1),
                io32(0x648) => common.gpu.gpu_3d_regs.get_clip_mtx_result(2),
                io32(0x64C) => common.gpu.gpu_3d_regs.get_clip_mtx_result(3),
                io32(0x650) => common.gpu.gpu_3d_regs.get_clip_mtx_result(4),
                io32(0x654) => common.gpu.gpu_3d_regs.get_clip_mtx_result(5),
                io32(0x658) => common.gpu.gpu_3d_regs.get_clip_mtx_result(6),
                io32(0x65C) => common.gpu.gpu_3d_regs.get_clip_mtx_result(7),
                io32(0x660) => common.gpu.gpu_3d_regs.get_clip_mtx_result(8),
                io32(0x664) => common.gpu.gpu_3d_regs.get_clip_mtx_result(9),
                io32(0x668) => common.gpu.gpu_3d_regs.get_clip_mtx_result(10),
                io32(0x66C) => common.gpu.gpu_3d_regs.get_clip_mtx_result(11),
                io32(0x670) => common.gpu.gpu_3d_regs.get_clip_mtx_result(12),
                io32(0x674) => common.gpu.gpu_3d_regs.get_clip_mtx_result(13),
                io32(0x678) => common.gpu.gpu_3d_regs.get_clip_mtx_result(14),
                io32(0x67C) => common.gpu.gpu_3d_regs.get_clip_mtx_result(15),
                io32(0x680) => common.gpu.gpu_3d_regs.get_vec_mtx_result(0),
                io32(0x684) => common.gpu.gpu_3d_regs.get_vec_mtx_result(1),
                io32(0x688) => common.gpu.gpu_3d_regs.get_vec_mtx_result(2),
                io32(0x68C) => common.gpu.gpu_3d_regs.get_vec_mtx_result(3),
                io32(0x690) => common.gpu.gpu_3d_regs.get_vec_mtx_result(4),
                io32(0x694) => common.gpu.gpu_3d_regs.get_vec_mtx_result(5),
                io32(0x698) => common.gpu.gpu_3d_regs.get_vec_mtx_result(6),
                io32(0x69C) => common.gpu.gpu_3d_regs.get_vec_mtx_result(7),
                io32(0x6A0) => common.gpu.gpu_3d_regs.get_vec_mtx_result(8),
                io32(0x1000) => common.gpu.gpu_2d_regs_b.get_disp_cnt(),
                io16(0x1008) => common.gpu.gpu_2d_regs_b.get_bg_cnt(0),
                io16(0x100A) => common.gpu.gpu_2d_regs_b.get_bg_cnt(1),
                io16(0x100C) => common.gpu.gpu_2d_regs_b.get_bg_cnt(2),
                io16(0x100E) => common.gpu.gpu_2d_regs_b.get_bg_cnt(3),
                io16(0x1048) => common.gpu.gpu_2d_regs_b.win_in,
                io16(0x104A) => common.gpu.gpu_2d_regs_b.win_out,
                io16(0x1050) => common.gpu.gpu_2d_regs_b.bld_cnt,
                io16(0x1052) => common.gpu.gpu_2d_regs_b.bld_alpha,
                io16(0x106C) => todo!(),
                io32(0x100000) => common.ipc.fifo_recv::<{ ARM9 }>(emu),
                io32(0x100010) => common.cartridge.get_rom_data_in::<{ ARM9 }>(emu),
                _ => {
                    if index == 3 {
                        debug_println!("{:?} unknown io port read at {:x}", ARM9, addr_offset);
                    }

                    bytes_window[index] = 0;
                }
            });
            index += 1;
        }
        T::from(u32::from_le_bytes([bytes_window[3], bytes_window[4], bytes_window[5], bytes_window[6]]))
    }

    pub fn write<T: Convert>(&mut self, addr_offset: u32, value: T, emu: &mut Emu) {
        let bytes = value.into().to_le_bytes();
        let bytes = &bytes[..mem::size_of::<T>()];
        /*
         * Use moving windows to handle reads and writes
         * |0|0|0|  x  |   x   |   x   |   x   |0|0|0|
         *         addr   + 1     + 2     + 3
         */
        let mut bytes_window = [0u8; 10];
        let mut mask_window = [0u8; 10];
        bytes_window[3..3 + mem::size_of::<T>()].copy_from_slice(bytes);
        mask_window[3..3 + mem::size_of::<T>()].fill(0xFF);

        let mut addr_offset_tmp = addr_offset;
        let mut index = 3usize;
        let common = get_common_mut!(emu);
        let mem = get_mem_mut!(emu);
        while (index - 3) < bytes.len() {
            io_ports_write!(match addr_offset + (index - 3) as u32 {
                io32(0x0) => common.gpu.gpu_2d_regs_a.set_disp_cnt(mask, value),
                io16(0x4) => common.gpu.set_disp_stat::<{ ARM9 }>(mask, value),
                io16(0x8) => common.gpu.gpu_2d_regs_a.set_bg_cnt(0, mask, value),
                io16(0xA) => common.gpu.gpu_2d_regs_a.set_bg_cnt(1, mask, value),
                io16(0xC) => common.gpu.gpu_2d_regs_a.set_bg_cnt(2, mask, value),
                io16(0xE) => common.gpu.gpu_2d_regs_a.set_bg_cnt(3, mask, value),
                io16(0x10) => common.gpu.gpu_2d_regs_a.set_bg_h_ofs(0, mask, value),
                io16(0x12) => common.gpu.gpu_2d_regs_a.set_bg_v_ofs(0, mask, value),
                io16(0x14) => common.gpu.gpu_2d_regs_a.set_bg_h_ofs(1, mask, value),
                io16(0x16) => common.gpu.gpu_2d_regs_a.set_bg_v_ofs(1, mask, value),
                io16(0x18) => common.gpu.gpu_2d_regs_a.set_bg_h_ofs(2, mask, value),
                io16(0x1A) => common.gpu.gpu_2d_regs_a.set_bg_v_ofs(2, mask, value),
                io16(0x1C) => common.gpu.gpu_2d_regs_a.set_bg_h_ofs(3, mask, value),
                io16(0x1E) => common.gpu.gpu_2d_regs_a.set_bg_v_ofs(3, mask, value),
                io16(0x20) => common.gpu.gpu_2d_regs_a.set_bg_pa(2, mask, value),
                io16(0x22) => common.gpu.gpu_2d_regs_a.set_bg_pb(2, mask, value),
                io16(0x24) => common.gpu.gpu_2d_regs_a.set_bg_pc(2, mask, value),
                io16(0x26) => common.gpu.gpu_2d_regs_a.set_bg_pd(2, mask, value),
                io32(0x28) => common.gpu.gpu_2d_regs_a.set_bg_x(2, mask, value),
                io32(0x2C) => common.gpu.gpu_2d_regs_a.set_bg_y(2, mask, value),
                io16(0x30) => common.gpu.gpu_2d_regs_a.set_bg_pa(3, mask, value),
                io16(0x32) => common.gpu.gpu_2d_regs_a.set_bg_pb(3, mask, value),
                io16(0x34) => common.gpu.gpu_2d_regs_a.set_bg_pc(3, mask, value),
                io16(0x36) => common.gpu.gpu_2d_regs_a.set_bg_pd(3, mask, value),
                io32(0x38) => common.gpu.gpu_2d_regs_a.set_bg_x(3, mask, value),
                io32(0x3C) => common.gpu.gpu_2d_regs_a.set_bg_y(3, mask, value),
                io16(0x40) => common.gpu.gpu_2d_regs_a.set_win_h(0, mask, value),
                io16(0x42) => common.gpu.gpu_2d_regs_a.set_win_h(1, mask, value),
                io16(0x44) => common.gpu.gpu_2d_regs_a.set_win_v(0, mask, value),
                io16(0x46) => common.gpu.gpu_2d_regs_a.set_win_v(1, mask, value),
                io16(0x48) => common.gpu.gpu_2d_regs_a.set_win_in(mask, value),
                io16(0x4A) => common.gpu.gpu_2d_regs_a.set_win_out(mask, value),
                io16(0x4C) => common.gpu.gpu_2d_regs_a.set_mosaic(mask, value),
                io16(0x50) => common.gpu.gpu_2d_regs_a.set_bld_cnt(mask, value),
                io16(0x52) => common.gpu.gpu_2d_regs_a.set_bld_alpha(mask, value),
                io8(0x54) => common.gpu.gpu_2d_regs_a.set_bld_y(value),
                io16(0x60) => common.gpu.get_renderer_mut().renderer_3d.set_disp_3d_cnt(mask, value),
                io32(0x64) => common.gpu.set_disp_cap_cnt(mask, value),
                io16(0x6C) => common.gpu.gpu_2d_regs_a.set_master_bright(mask, value),
                io32(0xB0) => self.dma.set_sad::<0>(mask, value),
                io32(0xB4) => self.dma.set_dad::<0>(mask, value),
                io32(0xB8) => self.dma.set_cnt::<0>(mask, value, emu),
                io32(0xBC) => self.dma.set_sad::<1>(mask, value),
                io32(0xC0) => self.dma.set_dad::<1>(mask, value),
                io32(0xC4) => self.dma.set_cnt::<1>(mask, value, emu),
                io32(0xC8) => self.dma.set_sad::<2>(mask, value),
                io32(0xCC) => self.dma.set_dad::<2>(mask, value),
                io32(0xD0) => self.dma.set_cnt::<2>(mask, value, emu),
                io32(0xD4) => self.dma.set_sad::<3>(mask, value),
                io32(0xD8) => self.dma.set_dad::<3>(mask, value),
                io32(0xDC) => self.dma.set_cnt::<3>(mask, value, emu),
                io32(0xE0) => self.dma.set_fill::<0>(mask, value),
                io32(0xE4) => self.dma.set_fill::<1>(mask, value),
                io32(0xE8) => self.dma.set_fill::<2>(mask, value),
                io32(0xEC) => self.dma.set_fill::<3>(mask, value),
                io16(0x100) => self.timers.set_cnt_l::<0>(mask, value),
                io16(0x102) => self.timers.set_cnt_h::<0>(mask, value, emu),
                io16(0x104) => self.timers.set_cnt_l::<1>(mask, value),
                io16(0x106) => self.timers.set_cnt_h::<1>(mask, value, emu),
                io16(0x108) => self.timers.set_cnt_l::<2>(mask, value),
                io16(0x10A) => self.timers.set_cnt_h::<2>(mask, value, emu),
                io16(0x10C) => self.timers.set_cnt_l::<3>(mask, value),
                io16(0x10E) => self.timers.set_cnt_h::<3>(mask, value, emu),
                io16(0x180) => common.ipc.set_sync_reg::<{ ARM9 }>(mask, value, emu),
                io16(0x184) => common.ipc.set_fifo_cnt::<{ ARM9 }>(mask, value, emu),
                io32(0x188) => common.ipc.fifo_send::<{ ARM9 }>(mask, value, emu),
                io16(0x1A0) => common.cartridge.set_aux_spi_cnt::<{ ARM9 }>(mask, value),
                io8(0x1A2) => common.cartridge.set_aux_spi_data::<{ ARM9 }>(value),
                io32(0x1A4) => common.cartridge.set_rom_ctrl::<{ ARM9 }>(mask, value, emu),
                io32(0x1A8) => common.cartridge.set_bus_cmd_out_l::<{ ARM9 }>(mask, value),
                io32(0x1AC) => common.cartridge.set_bus_cmd_out_h::<{ ARM9 }>(mask, value),
                io8(0x208) => get_cpu_regs_mut!(emu, ARM9).set_ime(value, get_cm_mut!(emu)),
                io32(0x210) => get_cpu_regs_mut!(emu, ARM9).set_ie(mask, value, get_cm_mut!(emu)),
                io32(0x214) => get_cpu_regs_mut!(emu, ARM9).set_irf(mask, value),
                io8(0x240) => mem.vram.set_cnt(0, value),
                io8(0x241) => mem.vram.set_cnt(1, value),
                io8(0x242) => mem.vram.set_cnt(2, value),
                io8(0x243) => mem.vram.set_cnt(3, value),
                io8(0x244) => mem.vram.set_cnt(4, value),
                io8(0x245) => mem.vram.set_cnt(5, value),
                io8(0x246) => mem.vram.set_cnt(6, value),
                io8(0x247) => mem.wram.set_cnt(value, emu),
                io8(0x248) => mem.vram.set_cnt(7, value),
                io8(0x249) => mem.vram.set_cnt(8, value),
                io16(0x280) => self.div_sqrt.set_div_cnt(mask, value),
                io32(0x290) => self.div_sqrt.set_div_numer_l(mask, value),
                io32(0x294) => self.div_sqrt.set_div_numer_h(mask, value),
                io32(0x298) => self.div_sqrt.set_div_denom_l(mask, value),
                io32(0x29C) => self.div_sqrt.set_div_denom_h(mask, value),
                io16(0x2B0) => self.div_sqrt.set_sqrt_cnt(mask, value),
                io32(0x2B8) => self.div_sqrt.set_sqrt_param_l(mask, value),
                io32(0x2BC) => self.div_sqrt.set_sqrt_param_h(mask, value),
                io8(0x300) => get_cpu_regs_mut!(emu, ARM9).set_post_flg(value),
                io16(0x304) => common.gpu.set_pow_cnt1(mask, value),
                io16(0x330) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(0, mask, value),
                io16(0x332) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(1, mask, value),
                io16(0x334) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(2, mask, value),
                io16(0x336) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(3, mask, value),
                io16(0x338) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(4, mask, value),
                io16(0x33A) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(5, mask, value),
                io16(0x33C) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(6, mask, value),
                io16(0x33E) => common.gpu.get_renderer_mut().renderer_3d.set_edge_color(7, mask, value),
                io32(0x350) => common.gpu.get_renderer_mut().renderer_3d.set_clear_color(mask, value),
                io16(0x354) => common.gpu.get_renderer_mut().renderer_3d.set_clear_depth(mask, value),
                io32(0x358) => common.gpu.get_renderer_mut().renderer_3d.set_fog_color(mask, value),
                io16(0x35C) => common.gpu.get_renderer_mut().renderer_3d.set_fog_offset(mask, value),
                io8(0x360) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(0, value),
                io8(0x361) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(1, value),
                io8(0x362) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(2, value),
                io8(0x363) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(3, value),
                io8(0x364) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(4, value),
                io8(0x365) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(5, value),
                io8(0x366) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(6, value),
                io8(0x367) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(7, value),
                io8(0x368) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(8, value),
                io8(0x369) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(9, value),
                io8(0x36A) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(10, value),
                io8(0x36B) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(11, value),
                io8(0x36C) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(12, value),
                io8(0x36D) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(13, value),
                io8(0x36E) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(14, value),
                io8(0x36F) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(15, value),
                io8(0x370) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(16, value),
                io8(0x371) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(17, value),
                io8(0x372) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(18, value),
                io8(0x373) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(19, value),
                io8(0x374) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(20, value),
                io8(0x375) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(21, value),
                io8(0x376) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(22, value),
                io8(0x377) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(23, value),
                io8(0x378) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(24, value),
                io8(0x379) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(25, value),
                io8(0x37A) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(26, value),
                io8(0x37B) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(27, value),
                io8(0x37C) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(28, value),
                io8(0x37D) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(29, value),
                io8(0x37E) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(30, value),
                io8(0x37F) => common.gpu.get_renderer_mut().renderer_3d.set_fog_table(31, value),
                io16(0x380) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(0, mask, value),
                io16(0x382) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(1, mask, value),
                io16(0x384) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(2, mask, value),
                io16(0x386) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(3, mask, value),
                io16(0x388) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(4, mask, value),
                io16(0x38A) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(5, mask, value),
                io16(0x38C) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(6, mask, value),
                io16(0x38E) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(7, mask, value),
                io16(0x390) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(8, mask, value),
                io16(0x392) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(9, mask, value),
                io16(0x394) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(10, mask, value),
                io16(0x396) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(11, mask, value),
                io16(0x398) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(12, mask, value),
                io16(0x39A) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(13, mask, value),
                io16(0x39C) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(14, mask, value),
                io16(0x39E) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(15, mask, value),
                io16(0x3A0) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(16, mask, value),
                io16(0x3A2) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(17, mask, value),
                io16(0x3A4) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(18, mask, value),
                io16(0x3A6) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(19, mask, value),
                io16(0x3A8) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(20, mask, value),
                io16(0x3AA) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(21, mask, value),
                io16(0x3AC) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(22, mask, value),
                io16(0x3AE) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(23, mask, value),
                io16(0x3B0) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(24, mask, value),
                io16(0x3B2) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(25, mask, value),
                io16(0x3B4) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(26, mask, value),
                io16(0x3B6) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(27, mask, value),
                io16(0x3B8) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(28, mask, value),
                io16(0x3BA) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(29, mask, value),
                io16(0x3BC) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(30, mask, value),
                io16(0x3BE) => common.gpu.get_renderer_mut().renderer_3d.set_toon_table(31, mask, value),
                io32(0x400) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x404) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x408) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x40C) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x410) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x414) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x418) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x41C) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x420) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x424) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x428) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x42C) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x430) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x434) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x438) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x43C) => common.gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu),
                io32(0x440) => common.gpu.gpu_3d_regs.set_mtx_mode(mask, value, emu),
                io32(0x444) => common.gpu.gpu_3d_regs.set_mtx_push(mask, value, emu),
                io32(0x448) => common.gpu.gpu_3d_regs.set_mtx_pop(mask, value, emu),
                io32(0x44C) => common.gpu.gpu_3d_regs.set_mtx_store(mask, value, emu),
                io32(0x450) => common.gpu.gpu_3d_regs.set_mtx_restore(mask, value, emu),
                io32(0x454) => common.gpu.gpu_3d_regs.set_mtx_identity(mask, value, emu),
                io32(0x458) => common.gpu.gpu_3d_regs.set_mtx_load44(mask, value, emu),
                io32(0x45C) => common.gpu.gpu_3d_regs.set_mtx_load43(mask, value, emu),
                io32(0x460) => common.gpu.gpu_3d_regs.set_mtx_mult44(mask, value, emu),
                io32(0x464) => common.gpu.gpu_3d_regs.set_mtx_mult43(mask, value, emu),
                io32(0x468) => common.gpu.gpu_3d_regs.set_mtx_mult33(mask, value, emu),
                io32(0x46C) => common.gpu.gpu_3d_regs.set_mtx_scale(mask, value, emu),
                io32(0x470) => common.gpu.gpu_3d_regs.set_mtx_trans(mask, value, emu),
                io32(0x480) => common.gpu.gpu_3d_regs.set_color(mask, value, emu),
                io32(0x484) => common.gpu.gpu_3d_regs.set_normal(mask, value, emu),
                io32(0x488) => common.gpu.gpu_3d_regs.set_tex_coord(mask, value, emu),
                io32(0x48C) => common.gpu.gpu_3d_regs.set_vtx16(mask, value, emu),
                io32(0x490) => common.gpu.gpu_3d_regs.set_vtx10(mask, value, emu),
                io32(0x494) => common.gpu.gpu_3d_regs.set_vtx_x_y(mask, value, emu),
                io32(0x498) => common.gpu.gpu_3d_regs.set_vtx_x_z(mask, value, emu),
                io32(0x49C) => common.gpu.gpu_3d_regs.set_vtx_y_z(mask, value, emu),
                io32(0x4A0) => common.gpu.gpu_3d_regs.set_vtx_diff(mask, value, emu),
                io32(0x4A4) => common.gpu.gpu_3d_regs.set_polygon_attr(mask, value, emu),
                io32(0x4A8) => common.gpu.gpu_3d_regs.set_tex_image_param(mask, value, emu),
                io32(0x4AC) => common.gpu.gpu_3d_regs.set_pltt_base(mask, value, emu),
                io32(0x4C0) => common.gpu.gpu_3d_regs.set_dif_amb(mask, value, emu),
                io32(0x4C4) => common.gpu.gpu_3d_regs.set_spe_emi(mask, value, emu),
                io32(0x4C8) => common.gpu.gpu_3d_regs.set_light_vector(mask, value, emu),
                io32(0x4CC) => common.gpu.gpu_3d_regs.set_light_color(mask, value, emu),
                io32(0x4D0) => common.gpu.gpu_3d_regs.set_shininess(mask, value, emu),
                io32(0x500) => common.gpu.gpu_3d_regs.set_begin_vtxs(mask, value, emu),
                io32(0x504) => common.gpu.gpu_3d_regs.set_end_vtxs(mask, value, emu),
                io32(0x540) => common.gpu.gpu_3d_regs.set_swap_buffers(mask, value, emu),
                io32(0x580) => common.gpu.gpu_3d_regs.set_viewport(mask, value, emu),
                io32(0x5C0) => common.gpu.gpu_3d_regs.set_box_test(mask, value, emu),
                io32(0x5C4) => common.gpu.gpu_3d_regs.set_pos_test(mask, value, emu),
                io32(0x5C8) => common.gpu.gpu_3d_regs.set_vec_test(mask, value, emu),
                io32(0x600) => common.gpu.gpu_3d_regs.set_gx_stat(mask, value),
                io32(0x1000) => common.gpu.gpu_2d_regs_b.set_disp_cnt(mask, value),
                io16(0x1008) => common.gpu.gpu_2d_regs_b.set_bg_cnt(0, mask, value),
                io16(0x100A) => common.gpu.gpu_2d_regs_b.set_bg_cnt(1, mask, value),
                io16(0x100C) => common.gpu.gpu_2d_regs_b.set_bg_cnt(2, mask, value),
                io16(0x100E) => common.gpu.gpu_2d_regs_b.set_bg_cnt(3, mask, value),
                io16(0x1010) => common.gpu.gpu_2d_regs_b.set_bg_h_ofs(0, mask, value),
                io16(0x1012) => common.gpu.gpu_2d_regs_b.set_bg_v_ofs(0, mask, value),
                io16(0x1014) => common.gpu.gpu_2d_regs_b.set_bg_h_ofs(1, mask, value),
                io16(0x1016) => common.gpu.gpu_2d_regs_b.set_bg_v_ofs(1, mask, value),
                io16(0x1018) => common.gpu.gpu_2d_regs_b.set_bg_h_ofs(2, mask, value),
                io16(0x101A) => common.gpu.gpu_2d_regs_b.set_bg_v_ofs(2, mask, value),
                io16(0x101C) => common.gpu.gpu_2d_regs_b.set_bg_h_ofs(3, mask, value),
                io16(0x101E) => common.gpu.gpu_2d_regs_b.set_bg_v_ofs(3, mask, value),
                io16(0x1020) => common.gpu.gpu_2d_regs_b.set_bg_pa(2, mask, value),
                io16(0x1022) => common.gpu.gpu_2d_regs_b.set_bg_pb(2, mask, value),
                io16(0x1024) => common.gpu.gpu_2d_regs_b.set_bg_pc(2, mask, value),
                io16(0x1026) => common.gpu.gpu_2d_regs_b.set_bg_pd(2, mask, value),
                io32(0x1028) => common.gpu.gpu_2d_regs_b.set_bg_x(2, mask, value),
                io32(0x102C) => common.gpu.gpu_2d_regs_b.set_bg_y(2, mask, value),
                io16(0x1030) => common.gpu.gpu_2d_regs_b.set_bg_pa(3, mask, value),
                io16(0x1032) => common.gpu.gpu_2d_regs_b.set_bg_pb(3, mask, value),
                io16(0x1034) => common.gpu.gpu_2d_regs_b.set_bg_pc(3, mask, value),
                io16(0x1036) => common.gpu.gpu_2d_regs_b.set_bg_pd(3, mask, value),
                io32(0x1038) => common.gpu.gpu_2d_regs_b.set_bg_x(3, mask, value),
                io32(0x103C) => common.gpu.gpu_2d_regs_b.set_bg_y(3, mask, value),
                io16(0x1040) => common.gpu.gpu_2d_regs_b.set_win_h(0, mask, value),
                io16(0x1042) => common.gpu.gpu_2d_regs_b.set_win_h(1, mask, value),
                io16(0x1044) => common.gpu.gpu_2d_regs_b.set_win_v(0, mask, value),
                io16(0x1046) => common.gpu.gpu_2d_regs_b.set_win_v(1, mask, value),
                io16(0x1048) => common.gpu.gpu_2d_regs_b.set_win_in(mask, value),
                io16(0x104A) => common.gpu.gpu_2d_regs_b.set_win_out(mask, value),
                io16(0x104C) => common.gpu.gpu_2d_regs_b.set_mosaic(mask, value),
                io16(0x1050) => common.gpu.gpu_2d_regs_b.set_bld_cnt(mask, value),
                io16(0x1052) => common.gpu.gpu_2d_regs_b.set_bld_alpha(mask, value),
                io8(0x1054) => common.gpu.gpu_2d_regs_b.set_bld_y(value),
                io16(0x106C) => common.gpu.gpu_2d_regs_b.set_master_bright(mask, value),
                _ => {
                    if index == 3 {
                        debug_println!("{:?} unknown io port write at {:x} with value {:x}", ARM9, addr_offset, value.into());
                    }
                }
            });
            index += 1;
        }
    }
}
