use crate::core::emu::{get_cm, get_common, get_common_mut, get_cpu_regs, get_cpu_regs_mut, get_mem, get_mem_mut, io_div_sqrt, io_div_sqrt_mut, io_dma, io_dma_mut, io_timers, io_timers_mut, Emu};
use crate::core::CpuType::ARM9;
use crate::utils::Convert;
use dsvita_macros::{io_read, io_write};

io_read!(
    IoArm9ReadLut,
    [
        (io32(0x0), |emu| get_common!(emu).gpu.gpu_2d_regs_a.get_disp_cnt()),
        (io16(0x4), |emu| get_common!(emu).gpu.get_disp_stat::<{ ARM9 }>()),
        (io16(0x6), |emu| get_common!(emu).gpu.v_count),
        (io16(0x8), |emu| get_common!(emu).gpu.gpu_2d_regs_a.get_bg_cnt(0)),
        (io16(0xA), |emu| get_common!(emu).gpu.gpu_2d_regs_a.get_bg_cnt(1)),
        (io16(0xC), |emu| get_common!(emu).gpu.gpu_2d_regs_a.get_bg_cnt(2)),
        (io16(0xE), |emu| get_common!(emu).gpu.gpu_2d_regs_a.get_bg_cnt(3)),
        (io16(0x48), |emu| get_common!(emu).gpu.gpu_2d_regs_a.win_in),
        (io16(0x4A), |emu| get_common!(emu).gpu.gpu_2d_regs_a.win_out),
        (io16(0x50), |emu| get_common!(emu).gpu.gpu_2d_regs_a.bld_cnt),
        (io16(0x52), |emu| get_common!(emu).gpu.gpu_2d_regs_a.bld_alpha),
        (io16(0x60), |emu| get_common!(emu).gpu.get_renderer().renderer_3d.get_disp_3d_cnt()),
        (io32(0x64), |emu| get_common!(emu).gpu.disp_cap_cnt),
        (io16(0x6C), |emu| get_common!(emu).gpu.gpu_2d_regs_a.master_bright),
        (io32(0xB0), |emu| io_dma!(emu, ARM9).get_sad::<0>()),
        (io32(0xB4), |emu| io_dma!(emu, ARM9).get_dad::<0>()),
        (io32(0xB8), |emu| io_dma!(emu, ARM9).get_cnt::<0>()),
        (io32(0xBC), |emu| io_dma!(emu, ARM9).get_sad::<1>()),
        (io32(0xC0), |emu| io_dma!(emu, ARM9).get_dad::<1>()),
        (io32(0xC4), |emu| io_dma!(emu, ARM9).get_cnt::<1>()),
        (io32(0xC8), |emu| io_dma!(emu, ARM9).get_sad::<2>()),
        (io32(0xCC), |emu| io_dma!(emu, ARM9).get_dad::<2>()),
        (io32(0xD0), |emu| io_dma!(emu, ARM9).get_cnt::<2>()),
        (io32(0xD4), |emu| io_dma!(emu, ARM9).get_sad::<3>()),
        (io32(0xD8), |emu| io_dma!(emu, ARM9).get_dad::<3>()),
        (io32(0xDC), |emu| io_dma!(emu, ARM9).get_cnt::<3>()),
        (io32(0xE0), |emu| io_dma!(emu, ARM9).get_fill::<0>()),
        (io32(0xE4), |emu| io_dma!(emu, ARM9).get_fill::<1>()),
        (io32(0xE8), |emu| io_dma!(emu, ARM9).get_fill::<2>()),
        (io32(0xEC), |emu| io_dma!(emu, ARM9).get_fill::<3>()),
        (io16(0x100), |emu| io_timers_mut!(emu, ARM9).get_cnt_l::<0>(get_cm!(emu))),
        (io16(0x102), |emu| io_timers!(emu, ARM9).get_cnt_h::<0>()),
        (io16(0x104), |emu| io_timers_mut!(emu, ARM9).get_cnt_l::<1>(get_cm!(emu))),
        (io16(0x106), |emu| io_timers!(emu, ARM9).get_cnt_h::<1>()),
        (io16(0x108), |emu| io_timers_mut!(emu, ARM9).get_cnt_l::<2>(get_cm!(emu))),
        (io16(0x10A), |emu| io_timers!(emu, ARM9).get_cnt_h::<2>()),
        (io16(0x10C), |emu| io_timers_mut!(emu, ARM9).get_cnt_l::<3>(get_cm!(emu))),
        (io16(0x10E), |emu| io_timers!(emu, ARM9).get_cnt_h::<3>()),
        (io16(0x130), |emu| get_common!(emu).input.get_key_input()),
        (io16(0x180), |emu| get_common!(emu).ipc.get_sync_reg::<{ ARM9 }>()),
        (io16(0x184), |emu| get_common!(emu).ipc.get_fifo_cnt::<{ ARM9 }>()),
        (io16(0x1A0), |emu| get_common!(emu).cartridge.get_aux_spi_cnt::<{ ARM9 }>()),
        (io8(0x1A2), |emu| get_common!(emu).cartridge.get_aux_spi_data::<{ ARM9 }>()),
        (io32(0x1A4), |emu| get_common!(emu).cartridge.get_rom_ctrl::<{ ARM9 }>()),
        (io8(0x208), |emu| get_cpu_regs!(emu, ARM9).ime),
        (io32(0x210), |emu| get_cpu_regs!(emu, ARM9).ie),
        (io32(0x214), |emu| get_cpu_regs!(emu, ARM9).irf),
        (io8(0x240), |emu| get_mem!(emu).vram.cnt[0]),
        (io8(0x242), |emu| get_mem!(emu).vram.cnt[1]),
        (io8(0x243), |emu| get_mem!(emu).vram.cnt[2]),
        (io8(0x241), |emu| get_mem!(emu).vram.cnt[3]),
        (io8(0x244), |emu| get_mem!(emu).vram.cnt[4]),
        (io8(0x245), |emu| get_mem!(emu).vram.cnt[5]),
        (io8(0x246), |emu| get_mem!(emu).vram.cnt[6]),
        (io8(0x247), |emu| get_mem!(emu).wram.cnt),
        (io8(0x248), |emu| get_mem!(emu).vram.cnt[7]),
        (io8(0x249), |emu| get_mem!(emu).vram.cnt[8]),
        (io16(0x280), |emu| io_div_sqrt!(emu).div_cnt),
        (io32(0x290), |emu| io_div_sqrt!(emu).get_div_numer_l()),
        (io32(0x294), |emu| io_div_sqrt!(emu).get_div_numer_h()),
        (io32(0x298), |emu| io_div_sqrt!(emu).get_div_denom_l()),
        (io32(0x29C), |emu| io_div_sqrt!(emu).get_div_denom_h()),
        (io32(0x2A0), |emu| io_div_sqrt_mut!(emu).get_div_result_l()),
        (io32(0x2A4), |emu| io_div_sqrt_mut!(emu).get_div_result_h()),
        (io32(0x2A8), |emu| io_div_sqrt_mut!(emu).get_divrem_result_l()),
        (io32(0x2AC), |emu| io_div_sqrt_mut!(emu).get_divrem_result_h()),
        (io16(0x2B0), |emu| io_div_sqrt!(emu).sqrt_cnt),
        (io32(0x2B4), |emu| io_div_sqrt_mut!(emu).get_sqrt_result()),
        (io32(0x2B8), |emu| io_div_sqrt!(emu).get_sqrt_param_l()),
        (io32(0x2BC), |emu| io_div_sqrt!(emu).get_sqrt_param_h()),
        (io8(0x300), |emu| get_cpu_regs!(emu, ARM9).post_flg),
        (io16(0x304), |emu| get_common!(emu).gpu.pow_cnt1),
        (io32(0x600), |emu| get_common!(emu).gpu.gpu_3d_regs.get_gx_stat()),
        (io32(0x604), |emu| get_common!(emu).gpu.gpu_3d_regs.get_ram_count()),
        (io32(0x620), |emu| get_common!(emu).gpu.gpu_3d_regs.get_pos_result(0)),
        (io32(0x624), |emu| get_common!(emu).gpu.gpu_3d_regs.get_pos_result(1)),
        (io32(0x628), |emu| get_common!(emu).gpu.gpu_3d_regs.get_pos_result(2)),
        (io32(0x62C), |emu| get_common!(emu).gpu.gpu_3d_regs.get_pos_result(3)),
        (io16(0x630), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_result(0)),
        (io16(0x632), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_result(1)),
        (io16(0x634), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_result(2)),
        (io32(0x640), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(0)),
        (io32(0x644), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(1)),
        (io32(0x648), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(2)),
        (io32(0x64C), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(3)),
        (io32(0x650), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(4)),
        (io32(0x654), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(5)),
        (io32(0x658), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(6)),
        (io32(0x65C), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(7)),
        (io32(0x660), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(8)),
        (io32(0x664), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(9)),
        (io32(0x668), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(10)),
        (io32(0x66C), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(11)),
        (io32(0x670), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(12)),
        (io32(0x674), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(13)),
        (io32(0x678), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(14)),
        (io32(0x67C), |emu| get_common_mut!(emu).gpu.gpu_3d_regs.get_clip_mtx_result(15)),
        (io32(0x680), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(0)),
        (io32(0x684), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(1)),
        (io32(0x688), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(2)),
        (io32(0x68C), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(3)),
        (io32(0x690), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(4)),
        (io32(0x694), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(5)),
        (io32(0x698), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(6)),
        (io32(0x69C), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(7)),
        (io32(0x6A0), |emu| get_common!(emu).gpu.gpu_3d_regs.get_vec_mtx_result(8)),
        (io32(0x1000), |emu| get_common!(emu).gpu.gpu_2d_regs_b.get_disp_cnt()),
        (io16(0x1008), |emu| get_common!(emu).gpu.gpu_2d_regs_b.get_bg_cnt(0)),
        (io16(0x100A), |emu| get_common!(emu).gpu.gpu_2d_regs_b.get_bg_cnt(1)),
        (io16(0x100C), |emu| get_common!(emu).gpu.gpu_2d_regs_b.get_bg_cnt(2)),
        (io16(0x100E), |emu| get_common!(emu).gpu.gpu_2d_regs_b.get_bg_cnt(3)),
        (io16(0x1048), |emu| get_common!(emu).gpu.gpu_2d_regs_b.win_in),
        (io16(0x104A), |emu| get_common!(emu).gpu.gpu_2d_regs_b.win_out),
        (io16(0x1050), |emu| get_common!(emu).gpu.gpu_2d_regs_b.bld_cnt),
        (io16(0x1052), |emu| get_common!(emu).gpu.gpu_2d_regs_b.bld_alpha),
        (io16(0x106C), |emu| get_common!(emu).gpu.gpu_2d_regs_b.master_bright),
    ]
);

io_read!(
    IoArm9ReadLutUpper,
    [
        (io32(0x100000), |emu| get_common_mut!(emu).ipc.fifo_recv::<{ ARM9 }>(emu)),
        (io32(0x100010), |emu| get_common_mut!(emu).cartridge.get_rom_data_in::<{ ARM9 }>(emu)),
    ]
);

io_write!(
    IoArm9WriteLut,
    [
        (io32(0x0), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_disp_cnt(mask, value)),
        (io16(0x4), |mask, value, emu| get_common_mut!(emu).gpu.set_disp_stat::<{ ARM9 }>(mask, value)),
        (io16(0x8), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_cnt(0, mask, value)),
        (io16(0xA), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_cnt(1, mask, value)),
        (io16(0xC), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_cnt(2, mask, value)),
        (io16(0xE), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_cnt(3, mask, value)),
        (io16(0x10), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_h_ofs(0, mask, value)),
        (io16(0x12), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_v_ofs(0, mask, value)),
        (io16(0x14), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_h_ofs(1, mask, value)),
        (io16(0x16), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_v_ofs(1, mask, value)),
        (io16(0x18), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_h_ofs(2, mask, value)),
        (io16(0x1A), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_v_ofs(2, mask, value)),
        (io16(0x1C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_h_ofs(3, mask, value)),
        (io16(0x1E), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_v_ofs(3, mask, value)),
        (io16(0x20), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pa(2, mask, value)),
        (io16(0x22), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pb(2, mask, value)),
        (io16(0x24), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pc(2, mask, value)),
        (io16(0x26), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pd(2, mask, value)),
        (io32(0x28), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_x(2, mask, value)),
        (io32(0x2C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_y(2, mask, value)),
        (io16(0x30), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pa(3, mask, value)),
        (io16(0x32), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pb(3, mask, value)),
        (io16(0x34), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pc(3, mask, value)),
        (io16(0x36), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_pd(3, mask, value)),
        (io32(0x38), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_x(3, mask, value)),
        (io32(0x3C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bg_y(3, mask, value)),
        (io16(0x40), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_h(0, mask, value)),
        (io16(0x42), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_h(1, mask, value)),
        (io16(0x44), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_v(0, mask, value)),
        (io16(0x46), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_v(1, mask, value)),
        (io16(0x48), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_in(mask, value)),
        (io16(0x4A), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_win_out(mask, value)),
        (io16(0x4C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_mosaic(mask, value)),
        (io16(0x50), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bld_cnt(mask, value)),
        (io16(0x52), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bld_alpha(mask, value)),
        (io8(0x54), |value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_bld_y(value)),
        (io16(0x60), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_disp_3d_cnt(mask, value)),
        (io32(0x64), |mask, value, emu| get_common_mut!(emu).gpu.set_disp_cap_cnt(mask, value)),
        (io16(0x6C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_a.set_master_bright(mask, value)),
        (io32(0xB0), |mask, value, emu| io_dma_mut!(emu, ARM9).set_sad::<0>(mask, value)),
        (io32(0xB4), |mask, value, emu| io_dma_mut!(emu, ARM9).set_dad::<0>(mask, value)),
        (io32(0xB8), |mask, value, emu| io_dma_mut!(emu, ARM9).set_cnt::<0>(mask, value, emu)),
        (io32(0xBC), |mask, value, emu| io_dma_mut!(emu, ARM9).set_sad::<1>(mask, value)),
        (io32(0xC0), |mask, value, emu| io_dma_mut!(emu, ARM9).set_dad::<1>(mask, value)),
        (io32(0xC4), |mask, value, emu| io_dma_mut!(emu, ARM9).set_cnt::<1>(mask, value, emu)),
        (io32(0xC8), |mask, value, emu| io_dma_mut!(emu, ARM9).set_sad::<2>(mask, value)),
        (io32(0xCC), |mask, value, emu| io_dma_mut!(emu, ARM9).set_dad::<2>(mask, value)),
        (io32(0xD0), |mask, value, emu| io_dma_mut!(emu, ARM9).set_cnt::<2>(mask, value, emu)),
        (io32(0xD4), |mask, value, emu| io_dma_mut!(emu, ARM9).set_sad::<3>(mask, value)),
        (io32(0xD8), |mask, value, emu| io_dma_mut!(emu, ARM9).set_dad::<3>(mask, value)),
        (io32(0xDC), |mask, value, emu| io_dma_mut!(emu, ARM9).set_cnt::<3>(mask, value, emu)),
        (io32(0xE0), |mask, value, emu| io_dma_mut!(emu, ARM9).set_fill::<0>(mask, value)),
        (io32(0xE4), |mask, value, emu| io_dma_mut!(emu, ARM9).set_fill::<1>(mask, value)),
        (io32(0xE8), |mask, value, emu| io_dma_mut!(emu, ARM9).set_fill::<2>(mask, value)),
        (io32(0xEC), |mask, value, emu| io_dma_mut!(emu, ARM9).set_fill::<3>(mask, value)),
        (io16(0x100), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_l::<0>(mask, value)),
        (io16(0x102), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_h::<0>(mask, value, emu)),
        (io16(0x104), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_l::<1>(mask, value)),
        (io16(0x106), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_h::<1>(mask, value, emu)),
        (io16(0x108), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_l::<2>(mask, value)),
        (io16(0x10A), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_h::<2>(mask, value, emu)),
        (io16(0x10C), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_l::<3>(mask, value)),
        (io16(0x10E), |mask, value, emu| io_timers_mut!(emu, ARM9).set_cnt_h::<3>(mask, value, emu)),
        (io16(0x180), |mask, value, emu| get_common_mut!(emu).ipc.set_sync_reg::<{ ARM9 }>(mask, value, emu)),
        (io16(0x184), |mask, value, emu| get_common_mut!(emu).ipc.set_fifo_cnt::<{ ARM9 }>(mask, value, emu)),
        (io32(0x188), |mask, value, emu| get_common_mut!(emu).ipc.fifo_send::<{ ARM9 }>(mask, value, emu)),
        (io16(0x1A0), |mask, value, emu| get_common_mut!(emu).cartridge.set_aux_spi_cnt::<{ ARM9 }>(mask, value)),
        (io8(0x1A2), |value, emu| get_common_mut!(emu).cartridge.set_aux_spi_data::<{ ARM9 }>(value)),
        (io32(0x1A4), |mask, value, emu| get_common_mut!(emu).cartridge.set_rom_ctrl::<{ ARM9 }>(mask, value, emu)),
        (io32(0x1A8), |mask, value, emu| get_common_mut!(emu).cartridge.set_bus_cmd_out_l::<{ ARM9 }>(mask, value)),
        (io32(0x1AC), |mask, value, emu| get_common_mut!(emu).cartridge.set_bus_cmd_out_h::<{ ARM9 }>(mask, value)),
        (io8(0x208), |value, emu| get_cpu_regs_mut!(emu, ARM9).set_ime(value, emu)),
        (io32(0x210), |mask, value, emu| get_cpu_regs_mut!(emu, ARM9).set_ie(mask, value, emu)),
        (io32(0x214), |mask, value, emu| get_cpu_regs_mut!(emu, ARM9).set_irf(mask, value)),
        (io8(0x240), |value, emu| get_mem_mut!(emu).vram.set_cnt(0, value, emu)),
        (io8(0x241), |value, emu| get_mem_mut!(emu).vram.set_cnt(1, value, emu)),
        (io8(0x242), |value, emu| get_mem_mut!(emu).vram.set_cnt(2, value, emu)),
        (io8(0x243), |value, emu| get_mem_mut!(emu).vram.set_cnt(3, value, emu)),
        (io8(0x244), |value, emu| get_mem_mut!(emu).vram.set_cnt(4, value, emu)),
        (io8(0x245), |value, emu| get_mem_mut!(emu).vram.set_cnt(5, value, emu)),
        (io8(0x246), |value, emu| get_mem_mut!(emu).vram.set_cnt(6, value, emu)),
        (io8(0x247), |value, emu| get_mem_mut!(emu).wram.set_cnt(value, emu)),
        (io8(0x248), |value, emu| get_mem_mut!(emu).vram.set_cnt(7, value, emu)),
        (io8(0x249), |value, emu| get_mem_mut!(emu).vram.set_cnt(8, value, emu)),
        (io16(0x280), |mask, value, emu| io_div_sqrt_mut!(emu).set_div_cnt(mask, value)),
        (io32(0x290), |mask, value, emu| io_div_sqrt_mut!(emu).set_div_numer_l(mask, value)),
        (io32(0x294), |mask, value, emu| io_div_sqrt_mut!(emu).set_div_numer_h(mask, value)),
        (io32(0x298), |mask, value, emu| io_div_sqrt_mut!(emu).set_div_denom_l(mask, value)),
        (io32(0x29C), |mask, value, emu| io_div_sqrt_mut!(emu).set_div_denom_h(mask, value)),
        (io16(0x2B0), |mask, value, emu| io_div_sqrt_mut!(emu).set_sqrt_cnt(mask, value)),
        (io32(0x2B8), |mask, value, emu| io_div_sqrt_mut!(emu).set_sqrt_param_l(mask, value)),
        (io32(0x2BC), |mask, value, emu| io_div_sqrt_mut!(emu).set_sqrt_param_h(mask, value)),
        (io8(0x300), |value, emu| get_cpu_regs_mut!(emu, ARM9).set_post_flg(value)),
        (io16(0x304), |mask, value, emu| get_common_mut!(emu).gpu.set_pow_cnt1(mask, value)),
        (io16(0x330), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(0, mask, value)),
        (io16(0x332), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(1, mask, value)),
        (io16(0x334), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(2, mask, value)),
        (io16(0x336), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(3, mask, value)),
        (io16(0x338), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(4, mask, value)),
        (io16(0x33A), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(5, mask, value)),
        (io16(0x33C), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(6, mask, value)),
        (io16(0x33E), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_edge_color(7, mask, value)),
        (io32(0x350), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_clear_color(mask, value)),
        (io16(0x354), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_clear_depth(mask, value)),
        (io32(0x358), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_color(mask, value)),
        (io16(0x35C), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_offset(mask, value)),
        (io8(0x360), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(0, value)),
        (io8(0x361), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(1, value)),
        (io8(0x362), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(2, value)),
        (io8(0x363), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(3, value)),
        (io8(0x364), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(4, value)),
        (io8(0x365), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(5, value)),
        (io8(0x366), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(6, value)),
        (io8(0x367), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(7, value)),
        (io8(0x368), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(8, value)),
        (io8(0x369), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(9, value)),
        (io8(0x36A), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(10, value)),
        (io8(0x36B), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(11, value)),
        (io8(0x36C), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(12, value)),
        (io8(0x36D), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(13, value)),
        (io8(0x36E), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(14, value)),
        (io8(0x36F), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(15, value)),
        (io8(0x370), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(16, value)),
        (io8(0x371), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(17, value)),
        (io8(0x372), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(18, value)),
        (io8(0x373), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(19, value)),
        (io8(0x374), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(20, value)),
        (io8(0x375), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(21, value)),
        (io8(0x376), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(22, value)),
        (io8(0x377), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(23, value)),
        (io8(0x378), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(24, value)),
        (io8(0x379), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(25, value)),
        (io8(0x37A), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(26, value)),
        (io8(0x37B), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(27, value)),
        (io8(0x37C), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(28, value)),
        (io8(0x37D), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(29, value)),
        (io8(0x37E), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(30, value)),
        (io8(0x37F), |value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_fog_table(31, value)),
        (io16(0x380), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(0, mask, value)),
        (io16(0x382), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(1, mask, value)),
        (io16(0x384), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(2, mask, value)),
        (io16(0x386), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(3, mask, value)),
        (io16(0x388), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(4, mask, value)),
        (io16(0x38A), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(5, mask, value)),
        (io16(0x38C), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(6, mask, value)),
        (io16(0x38E), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(7, mask, value)),
        (io16(0x390), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(8, mask, value)),
        (io16(0x392), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(9, mask, value)),
        (io16(0x394), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(10, mask, value)),
        (io16(0x396), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(11, mask, value)),
        (io16(0x398), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(12, mask, value)),
        (io16(0x39A), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(13, mask, value)),
        (io16(0x39C), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(14, mask, value)),
        (io16(0x39E), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(15, mask, value)),
        (io16(0x3A0), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(16, mask, value)),
        (io16(0x3A2), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(17, mask, value)),
        (io16(0x3A4), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(18, mask, value)),
        (io16(0x3A6), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(19, mask, value)),
        (io16(0x3A8), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(20, mask, value)),
        (io16(0x3AA), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(21, mask, value)),
        (io16(0x3AC), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(22, mask, value)),
        (io16(0x3AE), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(23, mask, value)),
        (io16(0x3B0), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(24, mask, value)),
        (io16(0x3B2), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(25, mask, value)),
        (io16(0x3B4), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(26, mask, value)),
        (io16(0x3B6), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(27, mask, value)),
        (io16(0x3B8), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(28, mask, value)),
        (io16(0x3BA), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(29, mask, value)),
        (io16(0x3BC), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(30, mask, value)),
        (io16(0x3BE), |mask, value, emu| get_common_mut!(emu).gpu.get_renderer_mut().renderer_3d.set_toon_table(31, mask, value)),
        (io32(0x400), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x404), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x408), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x40C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x410), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x414), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x418), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x41C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x420), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x424), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x428), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x42C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x430), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x434), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x438), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x43C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_fifo(mask, value, emu)),
        (io32(0x440), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_mode(mask, value, emu)),
        (io32(0x444), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_push(mask, value, emu)),
        (io32(0x448), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_pop(mask, value, emu)),
        (io32(0x44C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_store(mask, value, emu)),
        (io32(0x450), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_restore(mask, value, emu)),
        (io32(0x454), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_identity(mask, value, emu)),
        (io32(0x458), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_load44(mask, value, emu)),
        (io32(0x45C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_load43(mask, value, emu)),
        (io32(0x460), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_mult44(mask, value, emu)),
        (io32(0x464), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_mult43(mask, value, emu)),
        (io32(0x468), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_mult33(mask, value, emu)),
        (io32(0x46C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_scale(mask, value, emu)),
        (io32(0x470), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_mtx_trans(mask, value, emu)),
        (io32(0x480), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_color(mask, value, emu)),
        (io32(0x484), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_normal(mask, value, emu)),
        (io32(0x488), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_tex_coord(mask, value, emu)),
        (io32(0x48C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx16(mask, value, emu)),
        (io32(0x490), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx10(mask, value, emu)),
        (io32(0x494), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx_x_y(mask, value, emu)),
        (io32(0x498), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx_x_z(mask, value, emu)),
        (io32(0x49C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx_y_z(mask, value, emu)),
        (io32(0x4A0), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vtx_diff(mask, value, emu)),
        (io32(0x4A4), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_polygon_attr(mask, value, emu)),
        (io32(0x4A8), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_tex_image_param(mask, value, emu)),
        (io32(0x4AC), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_pltt_base(mask, value, emu)),
        (io32(0x4C0), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_dif_amb(mask, value, emu)),
        (io32(0x4C4), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_spe_emi(mask, value, emu)),
        (io32(0x4C8), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_light_vector(mask, value, emu)),
        (io32(0x4CC), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_light_color(mask, value, emu)),
        (io32(0x4D0), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_shininess(mask, value, emu)),
        (io32(0x500), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_begin_vtxs(mask, value, emu)),
        (io32(0x504), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_end_vtxs(mask, value, emu)),
        (io32(0x540), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_swap_buffers(mask, value, emu)),
        (io32(0x580), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_viewport(mask, value, emu)),
        (io32(0x5C0), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_box_test(mask, value, emu)),
        (io32(0x5C4), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_pos_test(mask, value, emu)),
        (io32(0x5C8), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_vec_test(mask, value, emu)),
        (io32(0x600), |mask, value, emu| get_common_mut!(emu).gpu.gpu_3d_regs.set_gx_stat(mask, value)),
        (io32(0x1000), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_disp_cnt(mask, value)),
        (io16(0x1008), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_cnt(0, mask, value)),
        (io16(0x100A), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_cnt(1, mask, value)),
        (io16(0x100C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_cnt(2, mask, value)),
        (io16(0x100E), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_cnt(3, mask, value)),
        (io16(0x1010), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_h_ofs(0, mask, value)),
        (io16(0x1012), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_v_ofs(0, mask, value)),
        (io16(0x1014), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_h_ofs(1, mask, value)),
        (io16(0x1016), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_v_ofs(1, mask, value)),
        (io16(0x1018), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_h_ofs(2, mask, value)),
        (io16(0x101A), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_v_ofs(2, mask, value)),
        (io16(0x101C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_h_ofs(3, mask, value)),
        (io16(0x101E), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_v_ofs(3, mask, value)),
        (io16(0x1020), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pa(2, mask, value)),
        (io16(0x1022), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pb(2, mask, value)),
        (io16(0x1024), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pc(2, mask, value)),
        (io16(0x1026), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pd(2, mask, value)),
        (io32(0x1028), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_x(2, mask, value)),
        (io32(0x102C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_y(2, mask, value)),
        (io16(0x1030), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pa(3, mask, value)),
        (io16(0x1032), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pb(3, mask, value)),
        (io16(0x1034), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pc(3, mask, value)),
        (io16(0x1036), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_pd(3, mask, value)),
        (io32(0x1038), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_x(3, mask, value)),
        (io32(0x103C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bg_y(3, mask, value)),
        (io16(0x1040), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_h(0, mask, value)),
        (io16(0x1042), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_h(1, mask, value)),
        (io16(0x1044), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_v(0, mask, value)),
        (io16(0x1046), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_v(1, mask, value)),
        (io16(0x1048), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_in(mask, value)),
        (io16(0x104A), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_win_out(mask, value)),
        (io16(0x104C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_mosaic(mask, value)),
        (io16(0x1050), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bld_cnt(mask, value)),
        (io16(0x1052), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bld_alpha(mask, value)),
        (io8(0x1054), |value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_bld_y(value)),
        (io16(0x106C), |mask, value, emu| get_common_mut!(emu).gpu.gpu_2d_regs_b.set_master_bright(mask, value)),
    ]
);

impl IoArm9WriteLut {
    pub fn write_fixed_slice<T: Convert>(addr: u32, slice: &[T], emu: &mut Emu) {
        let lut_addr = addr - Self::MIN_ADDR;
        let (func, write_size, offset) = unsafe { Self::_LUT.get_unchecked(lut_addr as usize) };

        if *write_size < size_of::<T>() as u8 {
            for value in slice {
                Self::write((*value).into(), addr, size_of::<T>() as u8, emu);
            }
        } else {
            let mask = 0xFFFFFFFF >> ((4 - size_of::<T>()) << 3);
            let mask = mask << *offset;
            for value in slice {
                let value = (*value).into() << *offset;
                func(mask, value, emu)
            }
        }
    }
}
